development:
  host: elasticsearch
  transport_options:
    request:
      timeout: 5

test:
  host: elasticsearch
  transport_options:
    request:
      timeout: 5

production:
  host: SEARCHBOX_URL
  transport_options:
    request:
      timeout: 5
