development:
  host: elasticsearch
  transport_options:
    request:
      timeout: 5

test:
  host: localhost

production:
  host: http://paas:e19c2e0f69188e15fc17f4a1b540e8bb@gloin-eu-west-1.searchly.com
  transport_options:
    request:
      timeout: 5
